### PR TITLE
Check if npm name is available (#4)

### PR DESCRIPTION
**Pull request by pablopunk**
🥇 👍

### CODE REVIEW

**Comment by pablopunk** [comment]
Oh that makes more sense, done!

**Comment by niftylettuce** [comment]
I will be publishing this shortly to NPM, working on documentation right now.

**Comment by niftylettuce** [comment]
@pablopunk See v0.1.1 published to npm.  Try `npm install -g lass@0.1.1` 👍

**Comment by niftylettuce** [comment]
@pablopunk I've added you as a contributor in `package.json`, see the auto generated section here with your name <https://github.com/lassjs/lass/#contributors>

**Comment by pablopunk** [comment]
@niftylettuce yay!! Thanks! I installed it and it works perfectly 👍

**Pull request merged**
