### PR TITLE
Add prerequisities to README

### PR DESCRIPTION
**Pull request by khriztianmoreno**
I add the basic prerequisites to be able to generate a template correctly

It is necessary to have version `^7.10.1` of [Node.JS](https://nodejs.org/) installed, since **lass** uses native [async/await](http://node.green/#ES2017-features-async-functions) to generate our template.

### CODE REVIEW

**Comment by niftylettuce** [comment]
Thanks @khriztianmoreno - can't we support Node v7.6.0+ actually instead of just Node v7.10.0+? <http://node.green/>

**Comment by khriztianmoreno** [comment]
@niftylettuce you are right, we can use version 7.6.0 which is the version that supports async await natively.

**Comment by niftylettuce** [comment]
@khriztianmoreno want to make another PR with the change?

**Comment by khriztianmoreno** [comment]
@niftylettuce yes, at one point I sent the pull request

**Pull request merged**
